name: CI/CD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - "**.py"  # Optional: Only run the workflow if Python files are changed

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ' 3.12.3'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        run: |
          # Add your Heroku deployment commands here
          echo "Deploying to Heroku"
